general.import = [
	#"~/.config/alacritty/catppuccin-macchiato.toml"
	# "~/.config/alacritty/catppuccin-mocha.toml"
    "~/.config/alacritty/one-dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"
opacity = 0.90

[font]
normal = { family = "Iosevka NFM", style = "Regular" }
bold = { family = "Iosevka NFM", style = "Bold" }
italic = { family = "Iosevka NFM", style = "Italic" }
bold_italic = { family = "Iosevka NFM", style = "Bold Italic" }
size = 12

